services:
  - type: web
    name: blii-docling-service
    env: docker
    plan: starter
    healthCheckPath: /healthz
    buildCommand: pip install -r requirements.txt
    startCommand: python3 docling_service.py
    envVars:
      - key: WEB_CONCURRENCY
        value: "1"
      - key: PORT
        value: "8080"
      - key: PYTHONUNBUFFERED
        value: "1"
