services:
  - type: web
    name: blii-docling-service
    env: docker
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: WEB_CONCURRENCY
        value: "1"
      - key: PORT
        value: "8080"
      - key: PYTHONUNBUFFERED
        value: "1"
